db:
  user: admin
  password: secret123
  host: postgres_company
  port: 5432
  database: company_db

server:
  port: ${PORT:80}

spring:
  application:
    name: company
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        type:
          preferred_instant_jdbc_type: TIMESTAMP
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${db.host}:${db.port}/${db.database}"
    password: ${db.password}
    username: ${db.user}
  flyway:
    baseline-on-migrate: true
    enabled: true
  main:
    allow-bean-definition-overriding: true

